swagger: '2.0'
info:
  description: Specification for PostSpot API
  version: ${version}
  title: PostSpot OpenAPI 3.0
  contact:
    email: postspot@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
basePath: /v1
schemes:
  - https
security:
  - api_key: []
x-google-management:
  metrics:
    - name: "get-requests"
      displayName: "get requests"
      valueType: INT64
      metricKind: DELTA
    - name: "post-requests"
      displayName: "post requests"
      valueType: INT64
      metricKind: DELTA
    - name: "put-requests"
      displayName: "put requests"
      valueType: INT64
      metricKind: DELTA
    - name: "delete-requests"
      displayName: "delete requests"
      valueType: INT64
      metricKind: DELTA
  quota:
    limits:
      - name: "get-limit"
        metric: "get-requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 10
      - name: "post-limit"
        metric: "post-requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 5
      - name: "put-limit"
        metric: "put-requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 3
      - name: "delete-limit"
        metric: "delete-requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 1
paths:
  /hello_user:
    get:
      x-google-backend:
        address: ${user_service_url}
        path_translation: APPEND_PATH_TO_ADDRESS
      summary: Displays user service hello page
      description: ''
      operationId: 'hello_user'
      responses:
        default:
          description: Default error sample response
  /hello_post:
    get:
      x-google-backend:
        address: ${post_service_url} 
        path_translation: APPEND_PATH_TO_ADDRESS
      summary: Displays post service hello page
      description: ''
      operationId: 'hello_post'
      responses:
        default:
          description: Default error sample response
  /hello_notification:
    get:
      x-google-backend:
        address: ${notification_service_url} 
        path_translation: APPEND_PATH_TO_ADDRESS
      summary: Displays notification service hello page
      description: ''
      operationId: 'hello_notification'
      responses:
        default:
          description: Default error sample response
  /users:
    post:
      operationId: "signup"
      x-google-backend:
        address: ${user_service_url}
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters: []
      responses:
        '200':
          description: Successful response
      summary: Signup
  /users/{followee_google_id}/followers:
    get:
      operationId: "get_followers"
      x-google-backend:
        address: ${user_service_url}
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
      - in: path
        type: string
        name: followee_google_id
        required: true
      responses:
        '200':
          description: Successful response
        '404':
          description: Not found
      summary: Get Followers
    post:
      operationId: "add_followers"
      x-google-backend:
        address: ${user_service_url}
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
      - in: path
        type: string
        name: followee_google_id
        required: true
      responses:
        '200':
          description: Successful response
        '404':
          description: Not found
      summary: Follow User
  /users/{follower_google_id}/followees:
    get:
      operationId: "get_followees"
      x-google-backend:
        address: ${user_service_url}
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
      - in: path
        type: string
        name: follower_google_id
        required: true
      responses:
        '200':
          description: Successful response
        '404':
          description: Not found
      summary: Get Followees
  /users/{follower_google_id}/followees/{followee_google_id}:
    delete:
      operationId: "delete_followees"
      x-google-backend:
        address: ${user_service_url}
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
      - in: path
        type: string
        name: follower_google_id
        required: true
      - in: path
        name: followee_google_id
        type: string
        required: true
      responses:
        '200':
          description: Successful response
        '404':
          description: Not found
      summary: Delete Followee
