swagger: '2.0'
info:
  description: Specification for PostSpot API
  version: 1.0.0
  title: PostSpot OpenAPI 3.0
  contact:
    email: postspot@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
basePath: /v1
schemes:
  - https
security:
  - api_key: []
x-google-management:
  metrics:
    - name: "get-requests"
      displayName: "get requests"
      valueType: INT64
      metricKind: DELTA
    - name: "post-requests"
      displayName: "post requests"
      valueType: INT64
      metricKind: DELTA
    - name: "put-requests"
      displayName: "put requests"
      valueType: INT64
      metricKind: DELTA
    - name: "delete-requests"
      displayName: "delete requests"
      valueType: INT64
      metricKind: DELTA
  quota:
    limits:
      - name: "get-limit"
        metric: "get-requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 10
      - name: "post-limit"
        metric: "post-requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 5
      - name: "put-limit"
        metric: "put-requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 3
      - name: "delete-limit"
        metric: "delete-requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 1
paths:
  /hello_user:
    get:
      x-google-backend:
        address: https://user-service-prod-w6bxxp65eq-lm.a.run.app
      summary: Displays user service hello page
      description: ''
      operationId: 'hello_user'
      responses:
        default:
          description: Default error sample response
  /hello_post:
    get:
      x-google-backend:
        address: https://post-service-prod-w6bxxp65eq-lm.a.run.app
      summary: Displays post service hello page
      description: ''
      operationId: 'hello_post'
      responses:
        default:
          description: Default error sample response
  /test_endpoint1:
    get:
      x-google-backend:
        address: https://user-service-prod-w6bxxp65eq-lm.a.run.app
      summary: Test endpoint
      description: ''
      operationId: 'test'
      responses:
        default:
          description: Default error sample response
  /users/*:
    get:
      x-google-backend:
        address: https://user-service-prod-w6bxxp65eq-lm.a.run.app
      summary: Test endpoint
      description: ''
      operationId: 'users'
      responses:
        default:
          description: Default error sample response

  
